services:
  - type: worker
    name: tempoai-celery-worker
    region: oregon
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery --app tasks worker --loglevel info --concurrency 4"
    autoDeploy: false
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.11"
      - key: CELERY_BROKER_URL
        fromService:
          name: tempoai-celery-redis
          type: redis
          property: connectionString
  - type: web
    name: tempoai-flower
    region: oregon
    plan: free
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery --app tasks flower --loglevel=info"
    autoDeploy: false
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.11"
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: tempoai-celery-redis
          property: connectionString
  - type: redis
    name: tempoai-celery-redis
    region: oregon
    plan: starter # we choose a plan with persistence to ensure tasks are not lost upon restart
    maxmemoryPolicy: noeviction # recommended policy for queues
    ipAllowList: [] # only allow internal connections
